###
# About/contact for the site author
#
# name of the author of the site
name = "Tae Geun Kim"
# description to display in the sidebar
description = "Graduate student who enjoy <span class=\"codinfox-changing-keywords\"><b class=\"visible\">Physics.</b><b class=\"hidden\">Mathematics.</b><b class=\"hidden\">Programming.</b></span>"

# the profile image of the author to display in the sidebar
gravatar = "e5f3fb08e472278f9e75820f62fb1352" # md5 hash of your email address # sidebar.html

# contact links to reach the author
#  - `name` is the font-awesome char name
#  - `path` is the link to follow 
contact = [
    { name = "github", path = "https://github.com/axect" },
    { name = "linkedin", path = "https://www.linkedin.com/in/tae-geun-kim" },
    { name = "facebook", path = "https://www.facebook.com/edeftg" },
    { name = "email", path = "mailto:axect@outlook.kr" }
]
