# The URL the site will be built for
base_url = "https://axect.github.io/blog-zola"

title = "Axect's Blog"
description = "Mathematics, Physics and Computations"
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

taxonomies = [
  {name = "tags", lang = "en"},
  {name = "tags", lang = "ko"},
  {name = "categories", feed = true, lang = "en"},
  {name = "categories", feed = true, lang = "ko"},
]

# The additional languages for the site.
# Example:
#     languages = [
#       {code = "fr", feed = true}, # there will be a feed for French content
#       {code = "fr", search = true}, # there will be a Search Index for French content
#       {code = "it"}, # there won't be a feed for Italian content
#     ]
#
languages = [
  {code = "ko", feed = true, search = false},
]

generate_feed = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "codinfox-zola"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
logo = "/profile.png"

version = "0.1.0"
copyrightyear = "2021"

# Plugins
mathjax = true # whether support mathjax
google_analytics_token = "" # a UA-00000000-1 like code or leave blank if you don't want google analytics
disqus_short_name = "axect" # leave blank if you don't want disqus

# Where are tags and categories displayed
tag_page = "/tags/"
category_page = "/categories/"

image = "/motion_2d.png"
caption = "2D path generated by <a href=\"https://github.com/Axect/least_action\">Algorithmic Least Action Principle</a>"

read_time = true